config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/index', to: 'home#index_json'

  resources :sessions

  resources :users do
    resources :photos do
      resources :comments
      resources :rates
      resources :hashtags
      collection do
        patch :update_priorities
      end
    end
    collection do
      get :search
      post :filter
    end
  end

  resources :accounts

  devise_for :accounts, :controllers => { omniauth_callbacks: 'accounts/omniauth_callbacks'}

  post '/upload', to: 'photos#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord

  enum sex: {male: 1, female: 2, agender: 3, androgyne: 4, bigender: 5,
            genderfluid: 6, genderqueer: 7, intersex: 8, neither: 9,
            trans: 10}
  belongs_to :role
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :rates
  has_and_belongs_to_many :preferences
  has_one :account, dependent: :destroy

  after_initialize :set_defaults
  after_commit :clear_cache, ThinkingSphinx::RealTime.callback_for(:user)

  def avatar
    Photo.find(avatar_id)
  end

  def self.get_sex_value_by_key(i)
    User.sexes.find {|obj| obj[1] == i}.first
  end

  def update_preferences(preferences)
    self.preferences = []
    preferences.each do |pref|
      self.preferences << Preference.find(pref[:id])
    end
  end

  def clear_cache
    Rails.cache.delete(cache_key)
  end

  # search engine
  def photo_comments
    res = ''
    photos.each do |photo|
      res += photo.comments.pluck(:text).join(' ') + ' '
    end
    res
  end

  # search engine
  def photo_tags
    res = ''
    photos.each do |photo|
      res += photo.hashtags.pluck(:tag).join(' ') + ' '
    end
    res
  end

  def self.filter(query, params)
    users = User.search query, star: true, limit: 35, rank_mode: :bm25, with: create_search_params(params)
    filter_by_preferences(users, params['preferences'])
  end

  private

  def set_defaults
    self.role ||= Role.find_by(title: 'user')
    self.avatar_id ||= 1
  end

  def cache_key
    "user_#{id}"
  end

  def self.create_search_params(params)
    searchParams = {}
    if params['height']
      searchParams['height'] = params['height']['min']..params['height']['max']
    end
    if params['weight']
      searchParams['weight'] = params['weight']['min']..params['weight']['max']
    end
    if params['age']
      searchParams['birth'] = Time.new(Time.now.year - params['age']['max'])..Time.new(Time.now.year - params['age']['min'])
    end
    if params['sex']
      searchParams['sex'] = User.get_sex_value_by_key(params['sex']['value'].to_i)
    end
    searchParams
  end

  def self.read_preferences(prefs)
    result = []
    unless prefs.nil?
      prefs.keys.each do |key|
        if prefs[key]
          result.push key
        end
      end
    end
    result
  end

  def self.filter_by_preferences(users, parametersPreferences)
    result = []
    preferences = read_preferences(parametersPreferences)
    if preferences.empty?
      result = users
    else
      preferences.each do |preference|
        users.each do |user|
          if user.preferences.pluck(:value).include?(preference)
            unless result.include?(user)
              result.push user
            end
          end
        end
      end
    end
    result
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    if current_account == nil
      redirect_to root_path
    elsif current_account.user.role.title == 'admin'
      respond_to do |format|
        format.html
        format.json {
          @users = User.all
          render json: @users
        }
      end
    else
      redirect_to current_account.user
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html
      format.json {
        render json: @user
      }
    end
  end

  # GET /users/new
  def new
    @user = User.new
    render json: @user
  end

  # GET /users/1/edit
  def edit
    respond_to do |format|
      format.html
      format.json {
        render json: @user
      }
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    local_params = user_params
    @user.update_preferences(params[:user][:preferences])
    if local_params[:sex].to_i > 0
      local_params[:sex] = User.get_sex_value_by_key(local_params[:sex].to_i)
    else
      local_params.delete(:sex)
    end

    if @user.update(local_params)
      render json: { user: @user, msg: 'User successfully updated', redirect_to: 'user_path' }
    else
      render json: { errors: @user.errors, msg: @user.errors.full_messages.join(', ')}, status: 422
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_account.user.role.name == 'admin'
      @user.destroy
      render json: {msg: 'User deleted'}
    else
      render json: {msg: 'Unauthorized'}, status: 401
    end
  end

  def search
    respond_to do |format|
      format.html
      format.json {
        @users = User.search(params[:query])
        render json: @users
      }
    end
  end

  def filter
    @users = User.filter(params[:query], params[:searchOptions])
    render json: @users
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :avatar_id, :birth, :weight, :height, :sex, :preferences)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def sexes_list(sexes = {})
    User.sexes.each {|sex| sexes[sex[1]] = {text: User.human_enum_name(:sex, sex.first), value: sex[1]}}
    sexes
  end

  def preferences_list
    Preference.all
  end
end

app/views/users/_form.html.erb
<div ng-controller="UserCtrl" class="user-edit">


  <div class="avatar-container">
    <img id="avatar" ng-click="editAvatar();" ng-src="{{user.avatar.url}}"/>

    <div id="avatar-modal" class="modal">
      <h2><%= t('setAvatar') %></h2>
      <div class="modal-content">
        <div class="gallery" >
          <div ng-repeat="photo in user.photos" class="gallery-image-container">
            <div class="gallery-image">
              <img ng-src="{{photo.url}}" class="avatar-variant" ng-click="setAvatar(photo);" after-render="setup"/>
            </div>
          </div>
        </div>
      </div>
    </div>

    <a class="btn" href="<%= edit_account_path %>"><%= t('.changePassword') %></a>
  </div>

  <form name="userEditForm" novalidate role="form">
    <div class="edit-form">
      <div class="field">
        <label for="user_name"><%= User.human_attribute_name('name') %>:</label>
        <input type="text" name="user[name]" id="user_name" ng-model="user.name">
      </div>

      <div class="field">
        <label for="user_birth"><%= User.human_attribute_name('birth') %>:</label>
        <input type="datetime" name="user[birth]" id="user_birth" ng-model="user.birth" placeholder="yyyy-MM-dd">
      </div>

      <div class="field">
        <label for="user_weight"><%= User.human_attribute_name('weight') %>:</label>
        <input type="number" name="user[weight]" id="user_weight" ng-model="user.weight">
      </div>

      <div class="field">
        <label for="user_height"><%= User.human_attribute_name('height') %>:</label>
        <input type="number" name="user[height]" id="user_height" ng-model="user.height">
      </div>

      <div class="field">
        <label><%= User.human_attribute_name('sex') %>:</label>
        <select name="user[sex]" id="user_sex" ng-model="user.sex" ng-value="user.sex">
          <% sexes_list.each do |sex|  %>
            <%= content_tag(:option, sex[1][:text], value: sex[0]) %>
          <% end %>
        </select>
      </div>

      <div class="field">
        <label><%= User.human_attribute_name('preferences') %>:</label>
        <div class="preferences">
          <% preferences_list.each do |preference|  %>
              <div class="preference">
                <input type="checkbox" name="<%= preference.value %>" id="<%= preference.value %>" value="<%= preference.id %>" ng-checked="checkPreference('<%= preference.id %>');">
                <%= label_tag(preference.value, preference.value, class: 'preference-label') %>
              </div>
          <% end %>
        </div>
      </div>



      <div class="actions">
        <button class="btn" ng-click="submit(userEditForm)"><%= t('submit') %></button>
      </div>
    </div>
  </form>
</div>

app/views/users/_slideshow.html.erb
<slick init-onload=true data="user.photos" autoplay="true" autoplay-speed="2000">
  <div ng-repeat="photo in user.photos">
    <img ng-src="{{photo.url}}">
  </div>
</slick>

app/views/users/_table.html.erb
<table>
  <thead>
    <tr>
      <td><button ng-click="sortPhotosByPriority();"><%= t('users.show.priority')%></button></td>
      <td><%= t('users.show.photo')%></td>
      <td><%= t('users.show.posted')%></td>
      <td><button ng-click="sortPhotosByRating();"><%= t('users.show.rating')%></button></td>
      <td><%= t('users.show.lastComment')%></td>
    </tr>
  </thead>
  <tbody>
    <tr ng-repeat="photo in user.photos">
      <td>{{photo.priority}}</td>
      <td class="photo-cell">
        <!--onpage image-->
        <div class="gallery-image">
          <p ng-hide="isDragDisabled">Priority: {{photo.priority}}</p>
          <a href="#photo{{photo.id}}" class="modal-trigger"><img ng-src="{{photo.url}}"/></a>
        </div>
      </td>
      <td>{{photo.created_at}}</td>
      <td>{{photo.rating}}</td>
      <td>{{photo.comments[photo.comments.length - 1].text}}</td>
    </tr>
  </tbody>
</table>

app/views/users/_tiles.html.erb
<div ng-show="currentAccountPermitted">
  <button class="btn" ng-click="editPriorities();" ng-show="isDragDisabled"><%= t('users.show.editPriorities')%></button>
  <button class="btn" ng-click="applyPriorities();" ng-hide="isDragDisabled"><%= t('users.show.apply')%></button>
  <button class="btn" ng-click="discardPriorities();" ng-hide="isDragDisabled"><%= t('users.show.discard')%></button>
</div>
<ul as-sortable="dragControlListeners" ng-model="user.photos" is-disabled="isDragDisabled">
  <li ng-repeat="photo in user.photos" as-sortable-item class="gallery-image-container">
    <div as-sortable-item-handle>
      <!--onpage image-->
      <div class="gallery-image">
        <p ng-hide="isDragDisabled">Priority: {{photo.priority}}</p>
        <a href="#photo{{photo.id}}" class="modal-trigger"><img ng-src="{{photo.url}}"/></a>
      </div>
    </div>
  </li>
</ul>

app/views/users/edit.html.erb
<h1><%= t('userEdit') %></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div ng-controller="UsersIndexCtrl">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>

  <table>
    <thead>
    <tr>
      <th><%= User.human_attribute_name('name') %></th>
      <th><%= User.human_attribute_name('avatar') %></th>
      <th><%= User.human_attribute_name('birth') %></th>
      <th><%= User.human_attribute_name('weight') %></th>
      <th><%= User.human_attribute_name('height') %></th>
      <th><%= User.human_attribute_name('sex') %></th>
      <th><%= User.human_attribute_name('role') %></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <tr ng-repeat="user in users">
      <td ng-bind="user.name"></td>
      <td>
        <div class="image-container">
          <img ng-src="{{user.avatar.url}}"/>
        </div>
      </td>
      <td ng-bind="user.birth | date:'dd.MM.yyyy'"></td>
      <td ng-bind="user.weight"></td>
      <td ng-bind="user.height"></td>
      <td ng-bind="user.sex"></td>
      <td ng-bind="user.role.title"></td>
      <td><a class="btn" href="users/{{user.id}}"><%= t('show') %></a></td>
      <td><a class="btn" href="users/{{user.id}}/edit"><%= t('edit') %></a></td>
      <td><button class="btn" ng-click="destroy(user)"><%= t('delete') %></button></td>
    </tr>
    </tbody>
  </table>
</div>

app/views/users/search.html.erb
<div ng-controller="searchCtrl">
  <p id="notice"><%= notice %></p>

  <h1><%= t('search') %></h1>

  <div class="input-field">
    <input id="search" type="search" ng-model="query" required>
    <label class="label-icon" for="search"><i class="material-icons">search</i></label>
    <i class="material-icons">close</i>
  </div>

  <table>
    <thead>
    <tr>
      <th><%= User.human_attribute_name('name') %></th>
      <th><%= User.human_attribute_name('avatar') %></th>
      <th><%= User.human_attribute_name('birth') %></th>
      <th><%= User.human_attribute_name('weight') %></th>
      <th><%= User.human_attribute_name('height') %></th>
      <th><%= User.human_attribute_name('sex') %></th>
      <th ng-show="isAdmin"><%= User.human_attribute_name('role') %></th>
      <th colspan="3" ng-show="isAdmin"></th>
    </tr>
    </thead>

    <tbody>
    <tr ng-repeat="user in users">
      <td class="username"><a href="/users/{{user.id}}"><h5>{{user.name}}</h5></a></td>
      <td>
        <div class="image-container">
          <img ng-src="{{user.avatar.url}}"/>
        </div>
      </td>
      <td ng-bind="user.birth | date:'dd.MM.yyyy'"></td>
      <td ng-bind="user.weight"></td>
      <td ng-bind="user.height"></td>
      <td ng-bind="user.sex"></td>
      <td ng-bind="user.role.title" ng-show="isAdmin"></td>
      <td><a class="btn" href="/users/{{user.id}}"><%= t('show') %></a></td>
      <td ng-show="isAdmin"><a class="btn" href="/users/{{user.id}}/edit"><%= t('edit') %></a></td>
      <td ng-show="isAdmin"><button class="btn" ng-click="destroy(user)"><%= t('delete') %></button></td>
    </tr>
    </tbody>
  </table>

  <div class="search-params">
    <form>
      <p class="range-field">
        <input id="age" type="checkbox" ng-model="searchOptions.age.asked">
        <label for="age"><%= User.human_attribute_name('age') %>:</label>
        <p>
          <input class="limit" type="number" ng-model="searchOptions.age.min">
          <span>-</span>
          <input class="limit" type="number" ng-model="searchOptions.age.max">
        </p>
        <div slider ng-from="searchOptions.age.min" ng-to="searchOptions.age.max" start="18" end="50"></div>
      </p>
      <p class="range-field">
        <input id="height" type="checkbox" ng-model="searchOptions.height.asked">
        <label for="height"><%= User.human_attribute_name('height') %>:</label>
        <p>
          <input class="limit" type="number" ng-model="searchOptions.height.min">
          <span>-</span>
          <input class="limit" type="number" ng-model="searchOptions.height.max">
        </p>
        <div slider ng-from="searchOptions.height.min" ng-to="searchOptions.height.max" start="100" end="250"></div>
      </p>
      <p class="range-field">
        <input id="weight" type="checkbox" ng-model="searchOptions.weight.asked">
        <label for="weight"><%= User.human_attribute_name('weight') %>:</label>
        <p>
          <input class="limit" type="number" ng-model="searchOptions.weight.min">
          <span>-</span>
          <input class="limit" type="number" ng-model="searchOptions.weight.max">
        </p>
        <div slider ng-from="searchOptions.weight.min" ng-to="searchOptions.weight.max" start="30" end="200"></div>
      </p>
      <p class="range-field">
        <input id="sex" type="checkbox" ng-model="searchOptions.sex.asked">
        <label for="sex"><%= User.human_attribute_name('sex') %>:</label>
        <select ng-model="searchOptions.sex.value">
          <% sexes_list.each do |sex|  %>
              <%= content_tag(:option, sex[1][:text], value: sex[0]) %>
          <% end %>
        </select>
      </p>
      <p class="range-field">
        <input id="preferences" type="checkbox" ng-model="searchOptions.preferences.asked">
        <label for="preferences"><%= User.human_attribute_name('preferences') %>: </label><br>
        <% preferences_list.each do |preference|  %>
          <input id="<%= preference.value %>" type="checkbox" ng-model="searchOptions.preferences.<%= preference.value %>"/>
          <%= label_tag(preference.value, preference.value) %>
        <% end %>
      </p>
      <button class="btn" ng-click="submit();"><%= t('submit') %></button>
    </form>
  </div>

</div>

app/views/users/show.html.erb
<div ng-controller="UserCtrl">
  <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
  <meta name="action-cable-url" content="ws://localhost:3000/cable"/>
  <p id="notice"><%= notice %></p>
  <h2 ng-bind="user.name"></h2>

  <div class="profile">

    <div class="row">
      <div class="col s12">
        <ul class="tabs">
          <li class="tab col s3"><a href="#profiletab"><%= t('.profile')%></a></li>
          <li class="tab col s3"><a class="active" href="#portfoliotab"><%= t('.portfolio')%></a></li>
        </ul>
      </div>
      <div id="profiletab" class="col s12">
        <div class="avatar-container">
          <img id="avatar" ng-click="editAvatar();" ng-src="{{user.avatar.url}}"/>
        </div>

        <div id="avatar-modal" class="modal">
          <h2><%= t('setAvatar') %></h2>
          <div class="modal-content">
            <div class="gallery" >
              <div ng-repeat="photo in user.photos" class="gallery-image-container">
                <div class="gallery-image">
                  <img ng-src="{{photo.url}}" class="avatar-variant" ng-click="setAvatar(photo);" after-render="setup"/>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="profile-info">
          <p>
            <strong><%= User.human_attribute_name('birth') %>:</strong>
            <span ng-bind="user.birth | date:'dd.MM.yyyy'"></span>
          </p>

          <p>
            <strong><%= User.human_attribute_name('weight') %>:</strong>
            <span ng-bind="user.weight"></span> <%= t('kg')%>
          </p>

          <p>
            <strong><%= User.human_attribute_name('height') %>:</strong>
            <span ng-bind="user.height"></span> <%= t('cm')%>
          </p>

          <p>
            <strong><%= User.human_attribute_name('sex') %>:</strong>
            <span ng-bind="user.sex"></span>
          </p>

          <p>
            <strong><%= User.human_attribute_name('preferences') %>:</strong>
            <span class="preference-label" ng-repeat="preference in user.preferences">{{preference.value}}</span>
          </p>
        </div>
      </div>
      <div id="portfoliotab" class="col s12">
        <div class="gallery-container">
          <div id="gallery-dropzone" ng-show="currentAccountPermitted">
            <form id="dropform" action="/upload" class="dropzone">
              <input type="hidden" name="user_id" ng-value="user.id"/>
            </form>
          </div>
          <div class="view-select">
            <p>
              <button class="btn" ng-click="show('table');"><%= t('.table')%></button>
              <button class="btn" ng-click="show('tiles');"><%= t('.tiles')%></button>
              <button class="btn" ng-click="show('slideshow');"><%= t('.slideshow')%></button>
            </p>
          </div>
          <div class="gallery">
            <div class="slideshow" ng-show="partial == 'slideshow'">
              <%= render 'slideshow' %>
            </div>
            <div class="table" ng-show="partial == 'table'">
              <%= render 'table' %>
            </div>
            <div class="tiles" ng-show="partial == 'tiles'">
              <%= render 'tiles' %>
            </div>
            <!--modals block-->
            <div ng-repeat="photo in user.photos" id="photo{{photo.id}}" class="modal">
              <div class="modal-content">
                <div class="modal-image">
                  <div class="modal-toolbar">
                    <div class="modal-hashtags" >
                      <div class="chip chip{{photo.id}}" ng-repeat="hashtag in photo.hashtags" ng-hide="hashtagEditMode">
                        #{{hashtag.tag}}
                      </div>
                      <div id="chips{{photo.id}}" class="chips chips-autocomplete" ng-show="currentAccountPermitted && hashtagEditMode">
                      </div>
                    </div>
                    <div class="modal-rating" ng-show="loggedIn">
                      <%= t('.rating') %>: {{photo.rating}}
                      <button class="btn-rating" ng-click="rate(photo, 1);">1</button>
                      <button class="btn-rating" ng-click="rate(photo, 2);">2</button>
                      <button class="btn-rating" ng-click="rate(photo, 3);">3</button>
                      <button class="btn-rating" ng-click="rate(photo, 4);">4</button>
                      <button class="btn-rating" ng-click="rate(photo, 5);">5</button>
                    </div>
                    <div class="modal-photo-controls" ng-show="currentAccountPermitted">
                      <button class="btn" ng-click="editHashtags();"><%= t('.editHashtags') %></button>
                      <button class="btn" ng-click="deletePhoto(user.id, photo);"><%= t('delete') %></button>
                    </div>
                  </div>
                  <img ng-src="{{photo.url}}"/>
                </div>
                <div class="modal-comments">
                  <p ng-repeat="comment in photo.comments">{{comment.user_name}} : {{comment.text}}</p>
                  <div class="comment-form">
                    <form name="commentForm" ng-controller="CommentsCtrl">
                      <input type="text" name="commentText" ng-model="commentText">
                      <button class="btn" ng-click="sendToCommentsChannel(commentText)" after-render="setup"><%= t('send') %></button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="<%= asset_path 'dropzone.js' %>"></script>
  <script src="<%= asset_path 'dropzone_setup.js.erb' %>"></script>
</div>