config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/index', to: 'home#index_json'

  resources :sessions

  resources :users do
    resources :photos do
      resources :comments
      resources :rates
      resources :hashtags
      collection do
        patch :update_priorities
      end
    end
    collection do
      get :search
      post :filter
    end
  end

  resources :accounts

  devise_for :accounts, :controllers => { omniauth_callbacks: 'accounts/omniauth_callbacks'}

  post '/upload', to: 'photos#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
  <head>
    <title>Portfl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <% if current_page?(controller: 'home', action: 'index') %>
    <div class="head">
      <h1>Portfl</h1>
      <h3>Lorem ipsum dolor sit amet</h3>
    </div>
  <% end %>

  <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo right">Portfl</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to t('home'), root_path %></li>
          <% if current_account %>
            <% if current_account.user.role.title == 'admin' %>
              <li><%= link_to t('navUsers'), users_path %></li>
            <% else %>
              <li><%= link_to t('profile'), user_path(current_account.user.id) %></li>
            <% end %>
            <li><%= t('currentlyLogin') %></li>
            <li><b><%= link_to current_account.user.name, edit_user_path(current_account.user.id) %></b></li>
            <li><%= button_to(t('logout'), current_account, :method => :delete) %> </li>
          <% else %>
            <li>
              <%= link_to t('signup'), new_session_path %>
            </li>
          <% end %>
          <li style="height: 64px;">
            <form ng-controller="searchformCtrl" ng-submit="navsearchSubmit();">
              <div class="input-field">
                <input id="search" type="search" ng-model="query" required>
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
              </div>
            </form>
          </li>
        </ul>
      </div>
    </nav>
    <p class="alert"><%= alert %></p>

    <div class="container"><%= yield %></div>
    <footer>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</footer>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </body>
</html>