config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/index', to: 'home#index_json'

  resources :sessions

  resources :users do
    resources :photos do
      resources :comments
      resources :rates
      resources :hashtags
      collection do
        patch :update_priorities
      end
    end
    collection do
      get :search
      post :filter
    end
  end

  resources :accounts

  devise_for :accounts, :controllers => { omniauth_callbacks: 'accounts/omniauth_callbacks'}

  post '/upload', to: 'photos#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauth_providers => [:facebook, :twitter, :vkontakte]
  validates :email,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            }
  belongs_to  :user

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |account|
      account.email ||= auth.info.email
    end
  end
end

app/controllers/accounts/omniauth_callbacks_controller.rb
class Accounts::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    login('Facebook')
  end

  def vkontakte
    login('Vkontakte')
  end

  def twitter
    login('Twitter')
  end

  private

  def login(kind)
    @account = Account.from_omniauth(request.env["omniauth.auth"])

    if @account.persisted?
      sign_in @account
      set_flash_message(:notice, :success, :kind => kind) if is_navigational_format?
      redirect_to '/'
    else
      render 'accounts/create'
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
    respond_to do |format|
      format.html
      format.json {
        render json: @account
      }
    end
  end

  def create
    @account = Account.new(account_params)
    puts account_params
    @account.user = User.new

    if @account.save
      sign_in @account
      render json: { account: @account.to_json, msg: 'Account successfully created', redirect_to: @account.user }
    else
      render json: { errors: @account.errors, msg: @account.errors.full_messages.join(', ')}, status: 422
    end
  end

  def edit
    if current_account.id != params[:id].to_i
      redirect_to '/'
    end
  end

  def show
    @account = Account.find(params[:id])
    respond_to do |format|
      format.html {
        redirect_to @account.user
      }
      format.json {
        if current_account == @account || current_account&.user.role.title == 'admin'
          render json: @account
        else
          render json: {}, status: 401
        end
      }
    end
  end

  def update
    if current_account.valid_password?(params[:oldPassword])
      puts 'password correct'
      if current_account.update(password: params[:newPassword])
        render json: {}, status: 200
      else
        render json: {msg: current_account.errors.full_messages.join(', ')}, status: 500
      end
    else
      render json: {msg: 'Old password doesn\'t correct'}, status: 401
    end
  end

  def destroy
    sign_out
    redirect_to '/'
  end

  private

  def account_params
    params.require(:account).permit(:email, :password, :uid, :provider)
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/views/accounts/create.html.erb
<h2><%= t('.registration') %></h2>

<%= form_for @account, url: accounts_path, method: :post do |f| %>
    <%= f.label :email, t(Account.human_attribute_name('email')) %>
    <%= f.email_field :email %>

    <%= f.label :password, t(Account.human_attribute_name('password')) %>
    <%= f.password_field :password %>

    <%= f.hidden_field :provider %>
    <%= f.hidden_field :uid %>
    <%= f.hidden_field :user_id %>
    <%= f.submit %>
<% end %>

app/views/accounts/edit.html.erb
<div ng-controller="accEditCtrl">
  <form name="accountEditForm">
    <div class="field">
      <label for="account_currentPassword"><%= t('.currentPassword') %></label>
      <input type="password" id="account_currentPassword" ng-model="currentPassword" required>
    </div>

    <div class="field">
      <label for="account_newPassword_1"><%= t('.newPassword') %></label>
      <input type="password" id="account_newPassword_1" ng-model="newPassword" required>
    </div>

    <div class="field">
      <label for="account_newPassword_2"><%= t('.newPasswordConfirm') %></label>
      <input type="password" id="account_newPassword_2" ng-model="newPasswordConfirm" required>
    </div>
    <div class="actions">
      <button class="btn" ng-click="submit(accountEditForm)" ng-disabled="!newPassword || newPassword != newPasswordConfirm"><%= t('submit') %></button>
    </div>
  </form>
</div>

app/views/accounts/new.html.erb
<div ng-controller="AccountCtrl">
  <form name="accountEditForm">
    <div class="field">
      <label for="account_email">Email</label>
      <input type="email" name="account[email]" id="account_email" ng-model="account.email">
    </div>

    <div class="field">
      <label for="account_password">Password</label>
      <input type="password" name="account[password]" id="account_password" ng-model="account.password">
    </div>
    <div class="actions">
      <button ng-click="submit(accountEditForm)">Submit</button>
    </div>
  </form>
</div>